// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXMby-2zt_ZXqx6dZOYqv5bjqA7YF7ag',
    appId: '1:988161204906:web:d1f0f8992d2168c587a6d3',
    messagingSenderId: '988161204906',
    projectId: 'messenger-e7785',
    authDomain: 'messenger-e7785.firebaseapp.com',
    storageBucket: 'messenger-e7785.appspot.com',
    measurementId: 'G-LK59LYW5GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGmA4KuyNN_hRPdEsViAfuAVQwR6H1ro',
    appId: '1:988161204906:android:17c74c5c0ced549287a6d3',
    messagingSenderId: '988161204906',
    projectId: 'messenger-e7785',
    storageBucket: 'messenger-e7785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMRYYu6He67AC6d30iTr-Bb7zIYmW8iHc',
    appId: '1:988161204906:ios:0d6565c7c219f85c87a6d3',
    messagingSenderId: '988161204906',
    projectId: 'messenger-e7785',
    storageBucket: 'messenger-e7785.appspot.com',
    iosClientId:
        '988161204906-mntlu8lf13rj9rqv8324mvf25dqb1jkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMRYYu6He67AC6d30iTr-Bb7zIYmW8iHc',
    appId: '1:988161204906:ios:0d6565c7c219f85c87a6d3',
    messagingSenderId: '988161204906',
    projectId: 'messenger-e7785',
    storageBucket: 'messenger-e7785.appspot.com',
    iosClientId:
        '988161204906-mntlu8lf13rj9rqv8324mvf25dqb1jkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );
}
